### ISSUE TITLE
Scroll status bar doesn't match up on first page

### ISSUE THREAD

**Issue by 2016rshah** [HackTJ/2016#1]
The red line doesn't reach the end of the first section. Was this intentional?

![screen shot 2015-11-29 at 8 43 45 pm](https://cloud.githubusercontent.com/assets/6821244/11461905/ec880024-96d9-11e5-9655-8b6ea30e6730.png)

**Comment by pandringa** [comment]
hmm that might be a cross-browser thing - it looks fine for me but I'll look into it.

**Comment by pandringa** [comment]
Fixed with bab17cf67f1907bca8e370e9350f26f88c884c2e
