### ISSUE TITLE
Scrolling line gets mixed up with scrolling in/out on the map

### ISSUE THREAD

**Issue by 2016rshah** [HackTJ/2016#2]
Scrolling has two functions on the page. The first is advancing the line, and the second is scrolling in/out on the map. If I scroll down quickly, the page scrolls until the mouse hits the map, then the map will scroll out. You also have to finagle your mouse outside of the map to get to the bottom of the page. This unexpected behavior also means that the user will accidentally scroll in/out of the map before seeing the popup that contains the location. This can be disorienting because you don't know what the original scale of the map was. 

What I would suggest is have a hover effect on the map. If the user clicks on the map, they can start interacting with it (scrolling, etc.). But otherwise, assume the user isn't trying to use the map, and they're just scrolling around the page.

**Comment by pandringa** [comment]
Yeah I was looking for Mapbox's official way to turn off scroll interactions, but I haven't been able to find one... I think they "intelligently" handle it but it still doesn't work well. 

Maybe we should disable all events then set a timer so if the user clicks or holds their mouse over it for ~2 seconds we turn on interactions?

**Comment by pandringa** [comment]
Just tried this in chrome and realized how bad it is - for whatever reason the scrolling in safari passes over the map unless you specifically stop and hover over it

**Comment by pandringa** [comment]
TODO: Use https://developers.google.com/maps/documentation/static-maps/?hl=en with custom styles + markers

**Comment by pandringa** [comment]
Fixed in bab17cf67f1907bca8e370e9350f26f88c884c2e

**Comment by pandringa** [comment]
Fixed in d1313df0b4d78cd0c3647b0965a72736eaf455d6
