### ISSUE TITLE
"Want to come" copy is not centered

### ISSUE THREAD

**Issue by 2016rshah** [HackTJ/2016#3]
On both the top and bottom of the screen, the text that says "Want to come? Registration is now open!" is not centered over the buttons it rests on. 

![screen shot 2015-11-29 at 8 49 06 pm](https://cloud.githubusercontent.com/assets/6821244/11461955/b3efaf86-96da-11e5-98fa-d15b197695f2.png)

![screen shot 2015-11-29 at 8 48 47 pm](https://cloud.githubusercontent.com/assets/6821244/11461954/b3eb5cec-96da-11e5-9861-09e242e8e265.png)

**Comment by pandringa** [comment]
That was kind of intentional - there was so much centered text that I wanted something to be left-justified to mix it up a little...

Does it bother you?
