### ISSUE TITLE
Background image isn't totally centered

### ISSUE THREAD

**Issue by 2016rshah** [HackTJ/2016#4]
I'm still on the fence about this background image. My initial reaction was that if we're not actually gonna hack at Monticello, we shouldn't have a picture of it. But it is nice and colorful, and kinda thematic I guess. 

Regardless, if we decide to stick with this picture, its not centered. The middle of the entrance is slightly to the right of the middle of the overlayed text. It is nit-picky, but it bothers me haha.

**Comment by pandringa** [comment]
hahaha the picture is actually a placeholder - Claire is going to take photos of the dome at night once the dome is finished (hopefully next week...)

We also talked about potentially setting up a gopro and getting a time-lapse of the dome as a background video
